apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: example
    spec:
      containers:
        - name: bb-site
          image: getting-started
          imagePullPolicy: Never
 ---
 apiVersion: v1
 kind: Service
 metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8090
    targetPort: 5000
    nodePort: 30001
