apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-coin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-coin-app
  template:
    metadata:
      labels:
        app: flask-coin-app
    spec:
      containers:
        - name: flask-coin-test-app
          image: docker.io/icyguy/k8s_classtask:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: flask-coin-service
spec:
  selector:
    app: flask-coin-app
  ports:
    - protocol: "TCP"
      port: 8090
  type: LoadBalancer
